package fr.imtatlantique.projet23.entity;

import java.util.Date;

public class Data {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.id
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.date
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.loch
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double loch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.latitude
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.longitude
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.surfHeading
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double surfheading;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.trueHeading
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double trueheading;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.velocity
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double velocity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.depth
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double depth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.aws
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double aws;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.tws
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double tws;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.awd
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double awd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.twd
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double twd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.airTemperature
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double airtemperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.atmPressure
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double atmpressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.humidity
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double humidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.sunPower
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double sunpower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.waterTemperature
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double watertemperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.salinity
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double salinity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.o2
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private Double o2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.missionName
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    private String missionname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.id
     *
     * @return the value of data_table.id
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.id
     *
     * @param id the value for data_table.id
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.date
     *
     * @return the value of data_table.date
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.date
     *
     * @param date the value for data_table.date
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.loch
     *
     * @return the value of data_table.loch
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getLoch() {
        return loch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.loch
     *
     * @param loch the value for data_table.loch
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setLoch(Double loch) {
        this.loch = loch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.latitude
     *
     * @return the value of data_table.latitude
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.latitude
     *
     * @param latitude the value for data_table.latitude
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.longitude
     *
     * @return the value of data_table.longitude
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.longitude
     *
     * @param longitude the value for data_table.longitude
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.surfHeading
     *
     * @return the value of data_table.surfHeading
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getSurfheading() {
        return surfheading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.surfHeading
     *
     * @param surfheading the value for data_table.surfHeading
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setSurfheading(Double surfheading) {
        this.surfheading = surfheading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.trueHeading
     *
     * @return the value of data_table.trueHeading
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getTrueheading() {
        return trueheading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.trueHeading
     *
     * @param trueheading the value for data_table.trueHeading
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setTrueheading(Double trueheading) {
        this.trueheading = trueheading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.velocity
     *
     * @return the value of data_table.velocity
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getVelocity() {
        return velocity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.velocity
     *
     * @param velocity the value for data_table.velocity
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setVelocity(Double velocity) {
        this.velocity = velocity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.depth
     *
     * @return the value of data_table.depth
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.depth
     *
     * @param depth the value for data_table.depth
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setDepth(Double depth) {
        this.depth = depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.aws
     *
     * @return the value of data_table.aws
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getAws() {
        return aws;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.aws
     *
     * @param aws the value for data_table.aws
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setAws(Double aws) {
        this.aws = aws;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.tws
     *
     * @return the value of data_table.tws
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getTws() {
        return tws;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.tws
     *
     * @param tws the value for data_table.tws
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setTws(Double tws) {
        this.tws = tws;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.awd
     *
     * @return the value of data_table.awd
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getAwd() {
        return awd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.awd
     *
     * @param awd the value for data_table.awd
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setAwd(Double awd) {
        this.awd = awd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.twd
     *
     * @return the value of data_table.twd
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getTwd() {
        return twd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.twd
     *
     * @param twd the value for data_table.twd
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setTwd(Double twd) {
        this.twd = twd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.airTemperature
     *
     * @return the value of data_table.airTemperature
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getAirtemperature() {
        return airtemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.airTemperature
     *
     * @param airtemperature the value for data_table.airTemperature
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setAirtemperature(Double airtemperature) {
        this.airtemperature = airtemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.atmPressure
     *
     * @return the value of data_table.atmPressure
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getAtmpressure() {
        return atmpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.atmPressure
     *
     * @param atmpressure the value for data_table.atmPressure
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setAtmpressure(Double atmpressure) {
        this.atmpressure = atmpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.humidity
     *
     * @return the value of data_table.humidity
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.humidity
     *
     * @param humidity the value for data_table.humidity
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setHumidity(Double humidity) {
        this.humidity = humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.sunPower
     *
     * @return the value of data_table.sunPower
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getSunpower() {
        return sunpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.sunPower
     *
     * @param sunpower the value for data_table.sunPower
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setSunpower(Double sunpower) {
        this.sunpower = sunpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.waterTemperature
     *
     * @return the value of data_table.waterTemperature
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getWatertemperature() {
        return watertemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.waterTemperature
     *
     * @param watertemperature the value for data_table.waterTemperature
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setWatertemperature(Double watertemperature) {
        this.watertemperature = watertemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.salinity
     *
     * @return the value of data_table.salinity
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getSalinity() {
        return salinity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.salinity
     *
     * @param salinity the value for data_table.salinity
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setSalinity(Double salinity) {
        this.salinity = salinity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.o2
     *
     * @return the value of data_table.o2
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public Double getO2() {
        return o2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.o2
     *
     * @param o2 the value for data_table.o2
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setO2(Double o2) {
        this.o2 = o2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.missionName
     *
     * @return the value of data_table.missionName
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public String getMissionname() {
        return missionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.missionName
     *
     * @param missionname the value for data_table.missionName
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    public void setMissionname(String missionname) {
        this.missionname = missionname == null ? null : missionname.trim();
    }
}