package fr.imtatlantique.projet23.web.dao;

import fr.imtatlantique.projet23.entity.Data;
import fr.imtatlantique.projet23.entity.DataExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface DataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    long countByExample(DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    int deleteByExample(DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    int insert(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    int insertSelective(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    List<Data> selectByExample(DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    Data selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") Data record, @Param("example") DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    int updateByExample(@Param("record") Data record, @Param("example") DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    int updateByPrimaryKeySelective(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbg.generated Sun Dec 06 16:12:51 CST 2020
     */
    int updateByPrimaryKey(Data record);

    List<Data> getDataByMissionName(Map map);

    List<String> getAllMissionNames();
}